version: '3.5'

services:
  db:
    image: postgres:latest
    container_name: supply_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: supply_db      
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
